apiVersion: apps/v1
kind: Deployment
metadata:
  name: ruv
spec:
  replicas: 7
  selector:
    matchLabels:
      app: ruv
  template:
    metadata:
      labels:
        app: ruv
    spec:
      containers:
      - name: ruv
        image: ruv:latest
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: ruv-service
spec:
  selector:
    app: ruv
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
