resources:
- name: my-instance
  type: compute.v1.instance
  properties:
    zone: us-central1-a
    machineType: zones/us-central1-a/machineTypes/n1-standard-1
    metadata:
      items:
      - key: startup-script
        value: |
          #! /bin/bash
          echo "Hello, world!" > /var/www/html/index.html
    networkInterfaces:
    - network: global/networks/default
      accessConfigs:
      - name: External NAT
        type: ONE_TO_ONE_NAT
    serviceAccounts:
    - email: default
      scopes:
      - https://www.googleapis.com/auth/cloud-platform

- name: my-instance-iam
  type: iam.v1.policy
  properties:
    resource: my-instance
    bindings:
    - role: roles/compute.instanceAdmin
      members:
      - serviceAccount:default

- name: my-instance-network
  type: compute.v1.network
  properties:
    autoCreateSubnetworks: true

- name: my-instance-firewall
  type: compute.v1.firewall
  properties:
    network: $(ref.my-instance-network.selfLink)
    allowed:
    - IPProtocol: TCP
      ports:
      - 80
    sourceRanges:
    - 0.0.0.0/0
