resources:
- name: my-vpc
  type: compute.v1.network
  properties:
    autoCreateSubnetworks: false

- name: my-subnet
  type: compute.v1.subnetwork
  properties:
    ipCidrRange: 10.0.0.0/16
    region: us-central1
    network: $(ref.my-vpc.selfLink)

- name: my-vpc-iam-policy
  type: gcp-types/cloudresourcemanager-v1:virtual.projects.iamMember
  properties:
    resource: my-gcp-project
    role: roles/compute.networkAdmin
    member: serviceAccount:my-service-account@my-gcp-project.iam.gserviceaccount.com

- name: my-vpc-iam-policy
  type: gcp-types/cloudresourcemanager-v1:virtual.projects.iamMember
  properties:
    resource: my-gcp-project
    role: roles/compute.securityAdmin
    member: serviceAccount:my-service-account@my-gcp-project.iam.gserviceaccount.com

outputs:
- name: networkURL
  value: $(ref.my-vpc.selfLink)
- name: subnetURL
  value: $(ref.my-subnet.selfLink)
